name: simple_safe_db
description: "A secure, in-memory database built on Dart with class-based functionality and detailed operation history tracking."
version: 0.0.1
repository: https://github.com/MasahideMori-SimpleAppli/simple_safe_db

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  file_state_manager: ^1.2.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  simple_jwt_manager: ^0.0.29

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

