name: simple_safe_db
description: "A secure, in-memory database built on Dart with class-based functionality and detailed operation history tracking."
version: 0.0.1
repository: https://github.com/MasahideMori-SimpleAppli/simple_safe_db

environment:
  sdk: ^3.8.1
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  file_state_manager: ^1.2.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
